#include "asmgen.h"

void generateAssembly(const std::vector<std::shared_ptr<Stmt>>& ast, std::ostream& out) {
    // Output simplified .asm stub
    out << "; Program.asm generated by Sage Compiler\n";
    out << "section .data\n";
    out << "    result dd 0\n";
    out << "section .text\n";
    out << "global _start\n";
    out << "_start:\n";
    out << "    ; [Pretend: compute a^3 + b^3 + 3*a^2*b + 3*a*b^2]\n";
    out << "    ; Compute result and store in 'result' variable\n";
    out << "    ; End of program\n";
    out << "    mov eax, 1\n";
    out << "    int 0x80\n";
}